### ISSUE TITLE
ITEM 07. 다 쓴 객체 참조를 해제하라

### ISSUE THREAD

**Issue by SGKIM94** [dolly0920/Effective_Java_Study#16]
- 간단한 자료구조나 리스너 혹은 콜백 등을 강한 참조와 약한 참조 등을 자유로운 주제로 비교하여 메모리 누수를 테스트한다.
- IntelliJ 에서 제공하는 Profilling 이나 tool 을 사용해서 확인해본다.
  - https://blog.jetbrains.com/idea/2020/03/profiling-tools-and-intellij-idea-ultimate/
  - https://stackoverflow.com/questions/19785290/java-unit-testing-how-to-measure-memory-footprint-for-method-call

**Comment by sypark9646** [comment]
뒤늦게 진도 따라잡고 있는데 [Java Reference와 GC](https://d2.naver.com/helloworld/329631) 이 글 좋네요
저에게는 와닿지 않았던.. `java.lang.ref` 패키지 예시도 나와 있구요, 그림 자료도 좋으니 한 번씩 보시면 좋을 듯 합니당!!
