### ISSUE TITLE
[ITEM 11 Extension] - 왜 hashCode 계산에는 31이 들어가는가?

### ISSUE THREAD

**Issue by VSFe** [dolly0920/Effective_Java_Study#25]
저 같은 무근본 코더는 별 이상한게 궁금합니다.

실제로 자바 라이브러리 내부에도 hashCode 계산에 31을 사용하는 경우가 잦습니다.

```java
// StringUTF16.java
public static int hashCode(byte[] value) {
    int h = 0;
    int length = value.length >> 1;
    for (int i = 0; i < length; i++) {
        h = 31 * h + getChar(value, i);
    }
    return h;
}
```

String은 내부 hashCode 연산을 수행할 때, 해당 문자열이 Latin 문자열인지에 따라 StringLatin1.hashCode() 또는 StringUTF16.hashCode() 중 하나를 실행하는데, 결과적으로 계산 과정은 유사합니다.

뭐... 책을 보셨으면 알겠지만, 이펙티브 자바에는 다음과 같은 말이 적혀있습니다.

> 곱할 숫자를 31로 정한 이유는 31이 홀수이면서 소수이기 때문이다.

**_그럼 왜 짝수면 안되고, 합성수면 안 되는걸까요?_**

숫자를 비트로 바꾸면, 짝수를 곱하는 것은 Shift 연산과 동일합니다. 즉, 맨 우측 숫자는 반드시 0으로 고정되게 되고, 이는 잠재적으로 가능한 숫자 범위에서 절반을 그냥 날려먹는 것과 동일한 결과를 냅니다. 따라서 충돌 가능성이 높아지는 것이죠.

그럼 합성수는 왜 안 될까요? 사실 결론만 말하면 **_상관 없긴 합니다._** 다만 이전부터 소수를 사용하려는 '경향'이 있기 때문에 (편견 같은거에요. 실제로는 성능 차이는 거의 없지만 홀수에서 최적화를 하려면 소수를 사용해야 한다는 신념 같은 기분이죠.)  사용하려고 합니다.
[여기](https://bytes.com/topic/c/answers/537762-why-mult-31-hash-function-string)를 보면, 다음과 같은 내용이 있습니다.

> First, the superstition: People who write code having to do with hash tables apparently recall that prime numbers are particularly "good" for them. It seems they don't always remember just what the "goodness" was or in what connection, but they'll throw prime numbers into the mix whenever they can. 

결국 소수를 사용하는 것은 일종의 신념 같은 거라고 이해하면 될 것 같습니다.

좋아요. 소수도 그렇고 짝수도 그렇고 좀 이해할 것 같습니다. 그럼 왜 31이죠? 결론만 말하면 **이전 어셈블러에서 최적화가 되기 때문입니다!** 어찌보면 이것도 옛날 관행을 따르다 보니 이렇게 된 기분이네요.

`RSB       r1, r0, r0, ASL #5    ; r1 := - r0 + (r0<<5)` 이런 식으로 표현되는데, 이는 일반적인 연산과 비교해서 횟수가 적기 때문에 시간이 적게 소모됩니다.

다만 이것도 옛 말입니다. 요즘은 컴파일러 최적화가 잘 되어서 31을 곱하는 것 보다 다른 소수를 곱하는게 더 빠른 경우도 있습니다! 하지만 충분히 무시할 수 있는 성능인 만큼 그냥 31 쓰는게 마음 편할 것 같네요... (사실 31을 곱하는 것 이외에도 다양한 라이브러리에는 수많은 방법을 소개하고 있습니다. Lombok 어노테이션도 다른 소수를 쓰고 있습니다!)

마지막으로, 명저 중 하나인 Introduction to Algorithm 3rd Edition (Thomas H. Cormen 외) 에는 다음과 같이 적혀 있습니다.
> As Exercise 11.3-3 asks you to show, choosing m D 2p | 1 when k is a character string interpreted in radix 2p may be a poor choice, because permuting the characters of k does not change its hash value.
A prime not too close to an exact power of 2 is often a good choice for m. 

여기를 따라 가면 오히려 31은 좋지 않은 수네요. 역시 해시는 다양한 방법이 있는 것 같습니다.

**Comment by sypark9646** [comment]
좋은 글 공유 해주셔서 감사합니다! 
저도 과거에 연산 횟수가 적어서 31을 택했었다는 것이 가장 설득력 있다고 생각이 들었어요ㅋㅋㅋ

그와 별개로 합성수도 막연하게 짝수와 마찬가지로 충돌 가능성이 높아질 줄 알았는데, 성능차이는 없군요... 배워갑니다!!
저도 관련 내용을 조금 더 서치 해 봐야겠어요 ㅎ.ㅎ
