### ISSUE TITLE
ITEM 19. 상속을 고려해 설계하고 문서화하라. 그러지 않았다면 상속을 금지하라

### ISSUE THREAD

**Issue by SGKIM94** [dolly0920/Effective_Java_Study#39]
아이템19에서는 상속을 사용했을 때 발생하는 `문제점` 과 상속을 꼭 사용해야하는 `조건` 과 상속을 사용을 해야한다고 했을 때 `해야할 일` 에 대해서 설명하고 있습니다.

각각 설명하고 있는 내용들을 정리해 봅시다.

1. 문제점
2. 조건
3. 해야할 일

**Comment by dolly0920** [comment]
https://chicken-run.tistory.com/3

**Comment by VSFe** [comment]
https://vsfe.tistory.com/36

**Comment by sypark9646** [comment]
https://sysgongbu.tistory.com/179
