### ISSUE TITLE
ITEM 20. 추상 클래스보다는 인터페이스를 우선하라

### ISSUE THREAD

**Issue by SGKIM94** [dolly0920/Effective_Java_Study#40]
ITEM19 와 연결하여 추상 클래스를 사용했을 때의 단점과 인터페이스를 사용할 수 있는 다양한 예시가 나와있습니다.
하지만 추상 클래스와 인터페이스의 차이에 대해서 명확히 정리가 되어있지는 않습니다.

1. 추상 클래스와 인터페이스의 차이에 대해서 정리
2. Java8 에 추가된 인터페이스의 기능과 그 이유 정리

를 해봅시다.

**Comment by dolly0920** [comment]
https://chicken-run.tistory.com/4

**Comment by VSFe** [comment]
https://vsfe.tistory.com/37

**Comment by sypark9646** [comment]
https://sysgongbu.tistory.com/181
