### ISSUE TITLE
ITEM 21. 인터페이스는 구현하는 쪽을 생각해 설계하라

### ISSUE THREAD

**Issue by SGKIM94** [dolly0920/Effective_Java_Study#41]
Java8 에서 추가된 인터페이스의 디폴트 메서드에 대해서 잘못된 예시와 어떻게 사용해야되는지 설명하고 있습니다.

Java8 에서 추가된 `디폴트 메서드` 와 `Lambda`, `Stream` 은 빠질 수 없는 주제인데요.
세가지의 핵심인 `Functional Interface` 에 대해서 알아보고 정리해봅시다.

**Comment by dolly0920** [comment]
https://chicken-run.tistory.com/5

**Comment by VSFe** [comment]
https://vsfe.tistory.com/38

**Comment by sypark9646** [comment]
https://sysgongbu.tistory.com/182
